Repository BfsoGourmet/webshop, pull requests merged in 2021-03, with the labels that each got.

#24 Feature/seeding
  app/Models/ProductCategory.php
  app/Models/ProductOrder.php
  app/Models/SpecialPrize.php
  app/Models/account.php
  app/Models/address.php
  app/Models/category.php
  app/Models/customer.php
  app/Models/declaration.php
  app/Models/manufacturer.php
  app/Models/order.php
  app/Models/status.php
  database/factories/AccountFactory.php
  database/factories/AddressFactory.php
  database/factories/CategoryFactory.php
  database/factories/CustomerFactory.php
  database/factories/DeclarationFactory.php
  database/factories/ManufacturerFactory.php
  database/factories/OrderFactory.php
  database/factories/ProductCategoryFactory.php
  database/factories/ProductFactory.php
  database/factories/ProductOrderFactory.php
  database/factories/SpecialPrizeFactory.php
  database/factories/StatusFactory.php
  database/migrations/2021_02_10_133015_create_manufacturers_table.php
  database/migrations/2021_02_10_133145_create_products_table.php
  database/migrations/2021_02_10_133221_create_accounts_table.php
  database/migrations/2021_02_10_133235_create_customers_table.php
  database/migrations/2021_02_10_133256_create_addresses_table.php
  database/migrations/2021_02_10_133312_create_statuses_table.php
  database/migrations/2021_02_10_133336_create_orders_table.php
  database/migrations/2021_02_10_133444_create_product_orders_table.php
  database/migrations/2021_02_10_133506_create_special_prizes_table.php
  database/migrations/2021_02_10_133524_create_categories_table.php
  database/migrations/2021_02_10_133554_create_product_categories_table.php
  database/migrations/2021_02_10_133610_create_declarations_table.php
  database/seeders/DatabaseSeeder.php
Labels: enhancement

#25 quickfix
  database/factories/SpecialPrizeFactory.php
  database/migrations/2021_02_10_133015_create_manufacturers_table.php
  database/migrations/2021_02_10_133145_create_products_table.php
  database/migrations/2021_02_10_133506_create_special_prizes_table.php
  database/migrations/2021_02_10_133524_create_categories_table.php
  database/migrations/2021_02_10_133554_create_product_categories_table.php
  database/migrations/2021_02_10_133610_create_declarations_table.php
Labels: bug

#26 Add laravel.yml
  .github/workflows/laravel.yml
Labels: enhancement

#28 Add Database Migration
  .github/workflows/laravel.yml
Labels: enhancement

#29 Feature/products overview
  app/Http/Controllers/ProductController.php
  public/Banner2.png
  public/Logo-f.png
  public/Logoweiss.png
  public/Schriftzug-weiss.png
  public/css/products.css
  resources/views/categories/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/pagination/default.blade.php
  resources/views/products/index.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: enhancement

#31 Add manufacture api
  app/Http/Controllers/Api/V1/ApiManufacturerController.php
  app/Http/Requests/ManufacturerRequest.php
  app/Models/manufacturer.php
  routes/api.php
Labels: enhancement

#32 Add installation instruction
  README.md
Labels: documentation

#33 Return orders
  app/Http/Controllers/Api/V1/ApiOrderController.php
  tests/Feature/ApiOrdersTest.php
Labels: enhancement
